2019-11-09 16:57:49,927 DEBUG   MainThread:17968 [wandb_config.py:_load_defaults():110] no defaults not found in config-defaults.yaml
2019-11-09 16:57:49,957 DEBUG   MainThread:17968 [util.py:is_cygwin_git():318] Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
2019-11-09 16:57:49,961 DEBUG   MainThread:17968 [cmd.py:execute():724] Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=<valid stream>)
2019-11-09 16:57:50,021 DEBUG   MainThread:17968 [cmd.py:execute():724] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-09 16:57:50,081 DEBUG   MainThread:17968 [cmd.py:execute():724] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-09 16:57:50,157 DEBUG   MainThread:17968 [run_manager.py:__init__():535] Initialized sync for kaistai607/wkzqv22m
2019-11-09 16:57:50,162 INFO    MainThread:17968 [run_manager.py:wrap_existing_process():1131] wrapping existing process 12900
2019-11-09 16:57:50,165 DEBUG   MainThread:17968 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): pypi.org:443
2019-11-09 16:57:50,745 DEBUG   MainThread:17968 [connectionpool.py:_make_request():437] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 37669
2019-11-09 16:57:50,936 INFO    Thread-7  :17968 [run_manager.py:_on_file_created():671] file/dir created: C:\Users\kyuree\dev\ai601\wandb\run-20191109_075748-wkzqv22m\wandb-metadata.json
2019-11-09 16:57:51,034 INFO    MainThread:17968 [run_manager.py:init_run():916] system metrics and metadata threads started
2019-11-09 16:57:51,034 INFO    MainThread:17968 [run_manager.py:init_run():950] upserting run before process can begin, waiting at most 10 seconds
2019-11-09 16:57:51,045 DEBUG   Thread-20 :17968 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-09 16:57:51,435 DEBUG   Thread-20 :17968 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 498
2019-11-09 16:57:51,451 INFO    Thread-20 :17968 [run_manager.py:_upsert_run():1035] saving patches
2019-11-09 16:57:51,452 DEBUG   Thread-20 :17968 [cmd.py:execute():724] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-09 16:57:51,542 DEBUG   Thread-20 :17968 [cmd.py:execute():724] Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-09 16:57:51,606 DEBUG   Thread-20 :17968 [cmd.py:execute():724] Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-09 16:57:51,701 DEBUG   Thread-20 :17968 [cmd.py:execute():724] Popen(['git', 'version'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
