2019-11-07 22:57:53,255 DEBUG   MainThread:13028 [wandb_config.py:_load_defaults():110] no defaults not found in config-defaults.yaml
2019-11-07 22:57:53,282 DEBUG   MainThread:13028 [util.py:is_cygwin_git():318] Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
2019-11-07 22:57:53,285 DEBUG   MainThread:13028 [cmd.py:execute():724] Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=<valid stream>)
2019-11-07 22:57:53,340 DEBUG   MainThread:13028 [cmd.py:execute():724] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-07 22:57:53,395 DEBUG   MainThread:13028 [cmd.py:execute():724] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-07 22:57:53,485 DEBUG   MainThread:13028 [run_manager.py:__init__():535] Initialized sync for ai607/uzn7ji5k
2019-11-07 22:57:53,490 INFO    MainThread:13028 [run_manager.py:wrap_existing_process():1131] wrapping existing process 2084
2019-11-07 22:57:53,492 DEBUG   MainThread:13028 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): pypi.org:443
2019-11-07 22:57:53,904 DEBUG   MainThread:13028 [connectionpool.py:_make_request():437] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 37669
2019-11-07 22:57:54,081 INFO    MainThread:13028 [run_manager.py:init_run():916] system metrics and metadata threads started
2019-11-07 22:57:54,088 INFO    MainThread:13028 [run_manager.py:init_run():950] upserting run before process can begin, waiting at most 10 seconds
2019-11-07 22:57:54,109 DEBUG   Thread-20 :13028 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-07 22:57:54,267 INFO    Thread-7  :13028 [run_manager.py:_on_file_created():671] file/dir created: C:\Users\kyuree\dev\ai601\models\wandb\run-20191107_135752-uzn7ji5k\output.log
2019-11-07 22:57:54,498 DEBUG   Thread-20 :13028 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 473
2019-11-07 22:57:54,521 INFO    Thread-20 :13028 [run_manager.py:_upsert_run():1035] saving patches
2019-11-07 22:57:54,521 DEBUG   Thread-20 :13028 [cmd.py:execute():724] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-07 22:57:54,612 DEBUG   Thread-20 :13028 [cmd.py:execute():724] Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-07 22:57:54,674 DEBUG   Thread-20 :13028 [cmd.py:execute():724] Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-07 22:57:54,784 DEBUG   Thread-20 :13028 [cmd.py:execute():724] Popen(['git', 'version'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-07 22:57:54,947 DEBUG   Thread-20 :13028 [cmd.py:execute():724] Popen(['git', 'merge-base', 'HEAD', '1dae055d2e6b66669489deaa42e5605845da4028'], cwd=C:\Users\kyuree\dev\ai601, universal_newlines=False, shell=None, istream=None)
2019-11-07 22:57:55,016 INFO    Thread-20 :13028 [run_manager.py:_upsert_run():1039] saving pip packages
2019-11-07 22:57:55,017 INFO    Thread-20 :13028 [run_manager.py:_upsert_run():1041] initializing streaming files api
2019-11-07 22:57:55,018 INFO    Thread-20 :13028 [run_manager.py:_upsert_run():1048] unblocking file change observer, beginning sync with W&B servers
2019-11-07 22:57:55,018 INFO    MainThread:13028 [run_manager.py:wrap_existing_process():1148] informing user process we are ready to proceed
2019-11-07 22:57:55,018 INFO    Thread-7  :13028 [run_manager.py:_on_file_created():671] file/dir created: C:\Users\kyuree\dev\ai601\models\wandb\run-20191107_135752-uzn7ji5k\wandb-metadata.json
2019-11-07 22:57:55,020 INFO    MainThread:13028 [run_manager.py:_sync_etc():1255] entering loop for messages from user process
2019-11-07 22:57:55,022 DEBUG   Thread-31 :13028 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-07 22:57:55,263 INFO    Thread-7  :13028 [run_manager.py:_on_file_modified():682] file/dir modified: C:\Users\kyuree\dev\ai601\models\wandb\run-20191107_135752-uzn7ji5k\output.log
2019-11-07 22:57:55,264 INFO    Thread-7  :13028 [run_manager.py:_on_file_modified():682] file/dir modified: C:\Users\kyuree\dev\ai601\models\wandb\run-20191107_135752-uzn7ji5k\config.yaml
2019-11-07 22:57:55,271 DEBUG   Thread-7  :13028 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-07 22:57:55,397 DEBUG   Thread-31 :13028 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 46
2019-11-07 22:57:55,506 INFO    MainThread:13028 [run_manager.py:_sync_etc():1278] received message from user process: {"exitcode": 1}
2019-11-07 22:57:55,506 INFO    MainThread:13028 [run_manager.py:_sync_etc():1364] closing log streams and sending exitcode to W&B
2019-11-07 22:57:55,506 INFO    MainThread:13028 [run_manager.py:shutdown():1055] shutting down system stats and metadata service
2019-11-07 22:57:55,655 DEBUG   Thread-7  :13028 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 521
2019-11-07 22:57:55,659 INFO    Thread-7  :13028 [run_manager.py:_on_file_created():671] file/dir created: C:\Users\kyuree\dev\ai601\models\wandb\run-20191107_135752-uzn7ji5k\requirements.txt
2019-11-07 22:57:55,660 INFO    Thread-7  :13028 [run_manager.py:_on_file_created():671] file/dir created: C:\Users\kyuree\dev\ai601\models\wandb\run-20191107_135752-uzn7ji5k\wandb-summary.json
2019-11-07 22:57:55,666 INFO    Thread-7  :13028 [run_manager.py:_on_file_created():671] file/dir created: C:\Users\kyuree\dev\ai601\models\wandb\run-20191107_135752-uzn7ji5k\diff.patch
2019-11-07 22:57:56,087 INFO    MainThread:13028 [run_manager.py:shutdown():1067] stopping streaming files and file change observer
2019-11-07 22:57:56,268 INFO    Thread-7  :13028 [run_manager.py:_on_file_modified():682] file/dir modified: C:\Users\kyuree\dev\ai601\models\wandb\run-20191107_135752-uzn7ji5k\output.log
2019-11-07 22:57:56,272 INFO    MainThread:13028 [run_manager.py:_on_file_modified():682] file/dir modified: C:\Users\kyuree\dev\ai601\models\wandb\run-20191107_135752-uzn7ji5k\wandb-summary.json
2019-11-07 22:57:56,274 INFO    MainThread:13028 [run_manager.py:_on_file_modified():682] file/dir modified: C:\Users\kyuree\dev\ai601\models\wandb\run-20191107_135752-uzn7ji5k\wandb-metadata.json
2019-11-07 22:57:56,275 INFO    MainThread:13028 [run_manager.py:_on_file_created():671] file/dir created: C:\Users\kyuree\dev\ai601\models\wandb\run-20191107_135752-uzn7ji5k\wandb-events.jsonl
2019-11-07 22:57:56,313 DEBUG   MainThread:13028 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-07 22:57:56,368 DEBUG   Thread-34 :13028 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-07 22:57:56,704 DEBUG   MainThread:13028 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 521
2019-11-07 22:57:56,771 DEBUG   Thread-34 :13028 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 753
2019-11-07 22:57:56,779 DEBUG   Thread-34 :13028 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): storage.googleapis.com:443
2019-11-07 22:57:57,279 DEBUG   Thread-34 :13028 [connectionpool.py:_make_request():437] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/sc2rl/ai607/uzn7ji5k/___batch_archive_1.tgz?Expires=1573135137&GoogleAccessId=gorilla-cloud-storage%40wandb-production.iam.gserviceaccount.com&Signature=EITkcKtPaLDLqjW2wy5ccmjs2ZlOETjxvAEDRjhvd9MGSo76rOWywsaFvsmsZZ90c2GMLBKfZbpWPcHrxQ0Av%2BMXGK3EcCjpCHunlOEePqC7C%2FVw4qcUni%2BEu3QkYzFPbYVr5dkLx%2B9iIN0Le9rKD6b2%2BkHSG2QyQ5nnQMeHJZzCRLOJIO%2FYHB9YI4z5K1AwrJAgH6gN6XRER%2Fwk1DPg1RIsGouh4HNP4ikY4lHEuXSYNPkYm2fOS%2BT7ZAuDXZidYw7hL1HwJNTX9wZ3614nFJIDFgNTuGRRXK%2Bjh53SGWeQssa2y0Pouu4SL2zpXNA440R5TFMvcvp2mtqul33O2A%3D%3D HTTP/1.1" 200 0
2019-11-07 22:57:57,298 DEBUG   Thread-13 :13028 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-07 22:57:57,333 DEBUG   Thread-35 :13028 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-07 22:57:57,710 DEBUG   Thread-13 :13028 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/sc2rl/ai607/uzn7ji5k/file_stream HTTP/1.1" 200 311
2019-11-07 22:57:57,724 DEBUG   Thread-35 :13028 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 755
2019-11-07 22:57:57,729 DEBUG   Thread-35 :13028 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): storage.googleapis.com:443
2019-11-07 22:57:57,939 DEBUG   Thread-13 :13028 [connectionpool.py:_make_request():437] https://api.wandb.ai:443 "POST /files/sc2rl/ai607/uzn7ji5k/file_stream HTTP/1.1" 200 308
2019-11-07 22:57:57,940 INFO    MainThread:13028 [run_manager.py:_sync_etc():1376] process only ran for 5 seconds, not syncing files
2019-11-07 22:57:57,940 INFO    MainThread:13028 [uzn7ji5k:run_manager.py:_sync_etc():1376] process only ran for 5 seconds, not syncing files
